/* empty css                      */import{S as q,i as u,a as E}from"./assets/vendor-DpA2_vLF.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v=new q(".gallery .gallery-link",{captionsData:"alt",captionDelay:250});function p(o){const r=o.map(({largeImageURL:n,webformatURL:i,tags:e,likes:t,views:a,comments:S,downloads:w})=>`<li class="gallery-item">
  <a class="gallery-link" href="${n}">
    <img class="gallery-image" src="${i}" alt="${e}"/>
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${t}</span></p>
    <p class="info-item"><b>Views</b> <span>${a}</span></p>
    <p class="info-item"><b>Comments</b> <span>${S}</span></p>
    <p class="info-item"><b>Downloads</b> <span>${w}</span></p>
  </div>
</li>`).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",r),v.refresh()}function I(){document.querySelector(".gallery").innerHTML=""}function f(){document.querySelector(".loader").classList.remove("is-hidden")}function d(){document.querySelector(".loader").classList.add("is-hidden")}function y(){document.querySelector(".pagination-btn").classList.remove("is-hidden")}function l(){document.querySelector(".pagination-btn").classList.add("is-hidden")}function M(){u.show({title:"Caution",message:"Search field cannot be empty. Please enter a keyword!",position:"topRight"})}function g(){u.error({title:"Sorry, ",message:"something wrong. Please try again!",position:"topRight"})}function h(){u.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function P(){u.warning({title:"Sorry",message:"there are no images matching your search query. Please try again!",position:"topRight"})}const B="56396197-05fcd5e3b9536b865c8ea6b88",T=15;async function b(o,r=1){return(await E.get("https://pixabay.com/api/",{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:T,page:r}})).data}const L={galleryEl:document.querySelector(".gallery"),formEl:document.querySelector(".form"),loadMoreEl:document.querySelector(".pagination-btn")};L.formEl.addEventListener("submit",$);L.loadMoreEl.addEventListener("click",z);let m=null,c=null,s=null;async function $(o){o.preventDefault(),I(),l(),f();const r=o.target.elements["search-text"].value.trim();if(!r){d(),M();return}m=r,c=1;try{const n=await b(m,c);if(s=n.hits.length,s===0){P();return}p(n.hits),s>=n.totalHits?(l(),h()):y()}catch{g()}finally{d()}}async function z(){c+=1,l(),f();try{const o=await b(m,c);p(o.hits),s+=o.hits.length;const i=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"}),s>=o.totalHits?(l(),h()):y()}catch{g()}finally{d()}}
//# sourceMappingURL=index.js.map
